#
# Module manifest for module 'Kestrel'
# Version: 1.0.0-beta4
# Generated by: Kestrun Contributors
# Generated on: 2026-01-27 08:01:31
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule             = 'Kestrun.psm1'

    # Version number of this module.
    ModuleVersion          = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID                   = 'fc7d511c-8ecc-4ed6-9480-3bba629bf5ff'

    # Author of this module
    Author                 = 'Kestrun Contributors'

    # Company or vendor of this module
    CompanyName            = 'Kestrun'

    # Copyright statement for this module
    Copyright              = 'Copyright © 2025–2026 Kestrun Contributors. All rights reserved.'

    # Description of the functionality provided by this module
    Description            = 'Kestrun is a cross-platform web server for ASP.NET Core. It is designed to be fast and lightweight, making it suitable for serving dynamic web applications and APIs.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion      = '7.4'

    # Name of the PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = '8.0'

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # ClrVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies  = @('lib/assemblies/Kestrun.Annotations.dll')

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess      = @(
        'Formats/Kestrun.Tasks.format.ps1xml'
    )

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport      = @(
        'Add-KrAddCallbacksAutomation', 'Add-KrAntiforgeryMiddleware', 'Add-KrAntiforgeryTokenRoute',
        'Add-KrApiDocumentationRoute', 'Add-KrApiKeyAuthentication', 'Add-KrBasicAuthentication',
        'Add-KrCacheMiddleware', 'Add-KrCacheResponse', 'Add-KrClaimPolicy',
        'Add-KrClientCertificateAuthentication', 'Add-KrCommonAccessLogMiddleware', 'Add-KrCompressionMiddleware',
        'Add-KrCookiesAuthentication', 'Add-KrCorsPolicy', 'Add-KrDistributedRedisCache',
        'Add-KrDistributedSqlServerCache', 'Add-KrEndpoint', 'Add-KrEnrichEnvironment',
        'Add-KrEnrichErrorRecord', 'Add-KrEnrichExceptionDetail', 'Add-KrEnrichFromLogContext',
        'Add-KrEnrichProcessId', 'Add-KrEnrichProcessName', 'Add-KrEnrichProperty',
        'Add-KrFaviconMiddleware', 'Add-KrFileServerMiddleware', 'Add-KrFormOption',
        'Add-KrFormRoute', 'Add-KrForwardedHeader', 'Add-KrGitHubAuthentication',
        'Add-KrHealthEndpoint', 'Add-KrHealthHttpProbe', 'Add-KrHealthProbe',
        'Add-KrHealthProcessProbe', 'Add-KrHostFiltering', 'Add-KrHsts',
        'Add-KrHtmlTemplateRoute', 'Add-KrHttpsRedirection', 'Add-KrJWTAudience',
        'Add-KrJWTBearerAuthentication', 'Add-KrJWTClaim', 'Add-KrJWTHeader',
        'Add-KrJWTIssuer', 'Add-KrJWTSubject', 'Add-KrListenUnixSocket',
        'Add-KrLocalizationMiddleware', 'Add-KrMapRoute', 'Add-KrNamedPipeListener',
        'Add-KrOAuth2Authentication', 'Add-KrOpenApiComponent', 'Add-KrOpenApiContact',
        'Add-KrOpenApiExtension', 'Add-KrOpenApiExternalDoc', 'Add-KrOpenApiInfo',
        'Add-KrOpenApiInline', 'Add-KrOpenApiLicense', 'Add-KrOpenApiRoute',
        'Add-KrOpenApiServer', 'Add-KrOpenApiTag', 'Add-KrOpenIdConnectAuthentication',
        'Add-KrPowerShellRazorPagesRuntime', 'Add-KrRazorPageService', 'Add-KrRequestDecompressionMiddleware',
        'Add-KrRouteGroup', 'Add-KrScheduling', 'Add-KrScriptBlock',
        'Add-KrSession', 'Add-KrSignalRHubMiddleware', 'Add-KrSinkConsole',
        'Add-KrSinkEventLog', 'Add-KrSinkFile', 'Add-KrSinkHttp',
        'Add-KrSinkPowerShell', 'Add-KrSinkSyslogLocal', 'Add-KrSinkSyslogTcp',
        'Add-KrSinkSyslogUdp', 'Add-KrSseBroadcastMiddleware', 'Add-KrStaticFilesMiddleware',
        'Add-KrTasksService', 'Add-KrUserClaim', 'Add-KrWindowsAuthentication',
        'Build-KrClaimPolicy', 'Build-KrJWT', 'Build-KrOpenApiDocument',
        'Clear-KrEnvironmentOverride', 'Clear-KrSession', 'Close-KrLogger',
        'ConvertFrom-KrJwkJsonToCertificate', 'ConvertFrom-KrYaml', 'ConvertTo-KrBase64Url',
        'ConvertTo-KrJwkJson', 'ConvertTo-KrYaml', 'Copy-KrJWTTokenBuilder',
        'Enable-KrConfiguration', 'Enable-KrExceptionHandling', 'Enable-KrStatusCodePage',
        'Expand-KrObject', 'Export-KrCertificate', 'Export-KrOpenApiDocument',
        'Get-KrBuiltTargetFrameworkVersion', 'Get-KrCertificatePurpose', 'Get-KrDefaultLogger',
        'Get-KrEnvironment', 'Get-KrFeatureSupport', 'Get-KrJwkThumbprint',
        'Get-KrJWTInfo', 'Get-KrJWTToken', 'Get-KrJWTValidationParameter',
        'Get-KrLocalizationCulture', 'Get-KrLocalizedString', 'Get-KrLoggerLevelSwitch',
        'Get-KrOpenApiDocument', 'Get-KrRequestBody', 'Get-KrRequestCookie',
        'Get-KrRequestForm', 'Get-KrRequestHeader', 'Get-KrRequestQuery',
        'Get-KrRequestRouteParam', 'Get-KrRoot', 'Get-KrScheduleReport',
        'Get-KrScheduleSnapshot', 'Get-KrServer', 'Get-KrSessionByte',
        'Get-KrSessionInt32', 'Get-KrSessionString', 'Get-KrSharedState',
        'Get-KrSignalRConnectedClient', 'Get-KrSinkJsonFormatter', 'Get-KrSseConnectedClientCount',
        'Get-KrTask', 'Get-KrTaskResult', 'Get-KrTaskState',
        'Get-KrVersion', 'Import-KrCertificate', 'Initialize-KrRoot',
        'Invoke-KrChallenge', 'Invoke-KrCookieSignIn', 'Invoke-KrCookieSignOut',
        'Invoke-KrWebRequest', 'Limit-KrJWTNotBefore', 'Limit-KrJWTValidity',
        'New-KrCertificateRequest', 'New-KrClaimPolicy', 'New-KrCookieBuilder',
        'New-KrCorsPolicyBuilder', 'New-KrFormPartRule', 'New-KrJWTBuilder',
        'New-KrLogger', 'New-KrMapRouteOption', 'New-KrOpenApiExample',
        'New-KrOpenApiExternalDoc', 'New-KrOpenApiHeader', 'New-KrOpenApiLink',
        'New-KrOpenApiServer', 'New-KrOpenApiServerVariable', 'New-KrPrivateKeyJwt',
        'New-KrProbeResult', 'New-KrSelfSignedCertificate', 'New-KrServer',
        'New-KrTask', 'NoDefault', 'Protect-KrJWT',
        'Protect-KrJWTPayload', 'Push-KrLogContextProperty', 'Register-KrLogger',
        'Register-KrSchedule', 'Remove-KrServer', 'Remove-KrSession',
        'Remove-KrSharedState', 'Remove-KrTask', 'Resolve-KrPath',
        'Resume-KrSchedule', 'Send-KrSignalREvent', 'Send-KrSignalRGroupMessage',
        'Send-KrSignalRLog', 'Send-KrSseBroadcastEvent', 'Set-KrCorsCredential',
        'Set-KrCorsExposedHeader', 'Set-KrCorsHeader', 'Set-KrCorsMethod',
        'Set-KrCorsOrigin', 'Set-KrCorsPreflightMaxAge', 'Set-KrDefaultLogger',
        'Set-KrEnvironment', 'Set-KrLoggerLevel', 'Set-KrLoggerLevelSwitch',
        'Set-KrPythonRuntime', 'Set-KrServerHttpsOptions', 'Set-KrServerLimit',
        'Set-KrServerNamedPipeOptions', 'Set-KrServerOptions', 'Set-KrSessionByte',
        'Set-KrSessionInt32', 'Set-KrSessionString', 'Set-KrSharedState',
        'Set-KrTaskName', 'Start-KrServer', 'Start-KrSseResponse',
        'Start-KrTask', 'Stop-KrServer', 'Stop-KrTask',
        'Suspend-KrSchedule', 'Test-KrCacheRevalidation', 'Test-KrCapability',
        'Test-KrCertificate', 'Test-KrDebugContext', 'Test-KrJWT',
        'Test-KrLogger', 'Test-KrOpenApiDocument', 'Test-KrRoute',
        'Update-KrJWT', 'Update-KrSynchronizedCounter', 'Write-KrBinaryResponse',
        'Write-KrBsonResponse', 'Write-KrCborResponse', 'Write-KrCsvResponse',
        'Write-KrErrorResponse', 'Write-KrFileResponse', 'Write-KrFormUrlEncodedResponse',
        'Write-KrHtmlResponse', 'Write-KrJsonResponse', 'Write-KrLog',
        'Write-KrRedirectResponse', 'Write-KrResponse', 'Write-KrSseEvent',
        'Write-KrStatusResponse', 'Write-KrStreamResponse', 'Write-KrTextResponse',
        'Write-KrXmlResponse', 'Write-KrYamlResponse'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport        = @()

    # Variables to export from this module
    VariablesToExport      = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport        = @(
        'ScriptBlock'
    )

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData            = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @(
                'powershell', 'web', 'server', 'http', 'https', 'listener', 'rest', 'api',
                'websites', 'powershell-core', 'windows', 'unix', 'linux', 'macos', 'cross-platform',
                'cross-platform', 'file-monitoring', 'multithreaded', 'schedule', 'middleware', 'session',
                'authentication', 'authorisation', 'arm', 'swagger', 'openapi', 'webserver', 'secrets', 'fim'
            )

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Kestrun/Kestrun/refs/heads/main/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Kestrun/Kestrun'

            # A URL to an icon representing this module.
            IconUri = 'https://www.kestrun.dev/assets/kestrun_favicon.ico'

            # ReleaseNotes of this module
            # ReleaseNotes = ''

            # Prerelease string of this module
            Prerelease = 'beta4'

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = False

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        } # End of PSData hashtable
    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
