version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/CSharp/Kestrun/"                # or "/src" if csproj lives deeper
    schedule:
      interval: "daily"
    commit-message:
      prefix: "🔼 NuGet"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "Microsoft.CodeAnalysis*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
