// ================================================
//   Kestrun OpenAPI Autogenerated Class Definitions
//   DO NOT EDIT - generated at runtime
// ================================================

public class Date : string
{
}

public class MuseumDailyHours
{
    public Date date { get; set; }
    public string timeOpen { get; set; }
    public string timeClose { get; set; }
}

public class GetMuseumHoursResponse : MuseumDailyHours
{
}

public class EventName : string
{
}

public class EventLocation : string
{
}

public class EventDescription : string
{
}

public class EventDates : Date
{
}

public class EventPrice : double
{
}

public class CreateSpecialEventRequest
{
    public EventName name { get; set; }
    public EventLocation location { get; set; }
    public EventDescription eventDescription { get; set; }
    public EventDates dates { get; set; }
    public EventPrice price { get; set; }
}

public class UpdateSpecialEventRequest
{
    public EventName name { get; set; }
    public EventLocation location { get; set; }
    public EventDescription eventDescription { get; set; }
    public EventDates dates { get; set; }
    public EventPrice price { get; set; }
}

public class eventId : string
{
}

public class SpecialEventResponse
{
    public eventId eventId { get; set; }
    public EventName name { get; set; }
    public EventLocation location { get; set; }
    public EventDescription eventDescription { get; set; }
    public EventDates dates { get; set; }
    public EventPrice price { get; set; }
}

public class SpecialEvent
{
    public string name { get; set; }
    public string location { get; set; }
    public string eventDescription { get; set; }
    public System.DateTime[] dates { get; set; }
    public double price { get; set; }
}

public class ListSpecialEventsResponse : SpecialEventResponse
{
}

public class TicketType : string
{
}

public class TicketId : string
{
}

public class TicketMessage : string
{
}

public class TicketConfirmation : string
{
}

public class Email : string
{
}

public class Phone : string
{
}

public class BuyMuseumTicketsRequest
{
    public TicketType ticketType { get; set; }
    public eventId eventId { get; set; }
    public Date ticketDate { get; set; }
    public Email email { get; set; }
    public Phone phone { get; set; }
}

public class BuyMuseumTicketsResponse
{
    public TicketMessage message { get; set; }
    public EventName eventName { get; set; }
    public TicketId ticketId { get; set; }
    public TicketType ticketType { get; set; }
    public Date ticketDate { get; set; }
    public TicketConfirmation confirmationCode { get; set; }
}

public class GetTicketCodeResponse
{
}

