name: ✨ Feature Request
description: Suggest an idea or enhancement for Kestrun
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Explain the problem or limitation you’re facing.
      placeholder: It’s hard to configure routes dynamically without...

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
      placeholder: Add a cmdlet `Add-KrRouteGroup` that...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered other approaches?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else we should know? Screenshots, examples, etc.
