name: 🔒 Security Issue
description: Report a security vulnerability in Kestrun (private & confidential)
labels: [security]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Important:** Please do not disclose security issues publicly.
        Use this form only if GitHub does not redirect you to the private security advisory flow.
        Otherwise, email us directly at **security@kestrun.dev**.

  - type: textarea
    id: vulnerability
    attributes:
      label: Vulnerability description
      description: Describe the security issue in detail.
      placeholder: Example: SQL injection in request parsing.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the vulnerability?

  - type: textarea
    id: impact
    attributes:
      label: Potential impact
      description: What could an attacker achieve with this vulnerability?
