<#
.SYNOPSIS
    Sets the schema name used for autogenerated OpenAPI client-error responses.
.DESCRIPTION
    Configures the OpenAPI descriptor to use a custom schema component name for
    autogenerated client-error responses (for example 400, 406, 415, 422).
.PARAMETER DocId
    One or more OpenAPI document IDs to configure. Defaults to the default document IDs.
.PARAMETER Name
    Schema component name to use for autogenerated client-error responses.
.PARAMETER ContentType
    One or more content types to use for autogenerated client-error responses.
    Defaults to application/problem+json.
.PARAMETER WhatIf
    Shows what would happen if the cmdlet runs. The cmdlet is not run.
.PARAMETER Confirm
    Prompts you for confirmation before running the cmdlet.
.EXAMPLE
    Set-KrOpenApiErrorSchema -Name 'ApiError'

    Uses 'ApiError' for autogenerated client-error response schemas in the default OpenAPI document.
.EXAMPLE
    Set-KrOpenApiErrorSchema -DocId @('Default','v2') -Name 'ApiError'

    Uses 'ApiError' for both Default and v2 OpenAPI documents.
.EXAMPLE
    Set-KrOpenApiErrorSchema -Name 'ApiError' -ContentType @('application/json','application/problem+json')

    Uses 'ApiError' and emits autogenerated client-error responses for both JSON media types.
.NOTES
    Set this before building/exporting OpenAPI output for predictable component naming.
#>
function Set-KrOpenApiErrorSchema {
    [KestrunRuntimeApi('Definition')]
    [CmdletBinding(SupportsShouldProcess = $true, ConfirmImpact = 'Low')]
    param(
        [Parameter()]
        [string[]]$DocId = [Kestrun.OpenApi.OpenApiDocDescriptor]::DefaultDocumentationIds,

        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [string]$Name,

        [Parameter()]
        [ValidateNotNullOrEmpty()]
        [string[]]$ContentType = @([Kestrun.OpenApi.OpenApiDocDescriptor]::DefaultAutoErrorResponseContentType)
    )

    $Server = Resolve-KestrunServer

    foreach ($doc in $DocId) {
        if ($PSCmdlet.ShouldProcess("OpenAPI document '$doc'", "Set auto error schema '$Name' with content types: $($ContentType -join ', ')")) {
            $descriptor = $Server.GetOrCreateOpenApiDocument($doc)
            $descriptor.AutoErrorResponseSchemaId = $Name
            $descriptor.AutoErrorResponseContentTypes = $ContentType
        }
    }
}
