[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSAvoidUsingWriteHost', '')]
param(
    [Parameter()]
    [string] $Project = '.\src\CSharp\Kestrun\Kestrun.csproj',
    [Parameter()]
    [string] $Path = '.\THIRD-PARTY-NOTICES.md',
    [Parameter()]
    [string] $FileVersion = './version.json'
)
Write-Host '📄 Generating third-party notices...'

# Add Helper utility module
Import-Module -Name './Utility/Modules/Helper.psm1'

# Ensure dotnet is available
if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    throw "The 'dotnet' CLI is not available on PATH. Install .NET SDK first."
}
try {
    $prevRollForward = $env:DOTNET_ROLL_FORWARD
    $env:DOTNET_ROLL_FORWARD = 'LatestMajor'
    # Ensure dotnet-project-licenses tool is installed
    if (-not (Get-Command dotnet-project-licenses -ErrorAction SilentlyContinue)) {
        Write-Host "📦 'dotnet-project-licenses' not found. Installing as a global tool..."
        dotnet tool install --global dotnet-project-licenses

        if ($LASTEXITCODE -ne 0) {
            throw "Failed to install 'dotnet-project-licenses' as a global tool."
        }

        # Re-check so we fail early if PATH/shims aren’t usable in this session
        if (-not (Get-Command dotnet-project-licenses -ErrorAction SilentlyContinue)) {
            throw "'dotnet-project-licenses' was installed, but the command is still not available on PATH in this session."
        }
    }


    # Get current version from version.json
    $Version = Get-Version -FileVersion $FileVersion

    # Get the licenses in markdown format
    $nugetLicenses = dotnet-project-licenses -i $Project -o markdown |
        Where-Object { $_ -notmatch '^\|\s+\|' } | # drop lines like "|    |..." with only whitespace between pipes
        ForEach-Object {
            if ($_ -match '^\|') {
                $cols = $_ -split '\|'
                if ($cols.Length -ge 4) {
                    # remove the two trailing "Error" / "Error Context" columns (they're before the final empty slot)
                    ($cols[0..($cols.Length - 4)] + $cols[-1]) -join '|'
                } else {
                    $_
                }
            } else {
                $_
            }
        }

} finally {
    if ($null -ne $prevRollForward) {
        $env:DOTNET_ROLL_FORWARD = $prevRollForward
    } else {
        Remove-Item Env:\DOTNET_ROLL_FORWARD -ErrorAction SilentlyContinue
    }
}
# Compose a soft, compliant introduction


$start = 2025
$now = (Get-Date).Year
$years = if ($start -eq $now) { $now } else { "$start–$now" }

$kestrunHeader = @"
<!--
  AUTO-GENERATED FILE — DO NOT EDIT.

  Project: Kestrun
  License: MIT
  Generated by: invoke-build ThirdPartyNotices
  Generated on: $((Get-Date).ToUniversalTime().ToString('o'))
  Commit: $(git rev-parse --short HEAD)
  Version: $Version

  To regenerate, run: .\Kestrun.build.ps1
  Do not modify manually; changes will be overwritten.
-->
<!-- markdownlint-disable MD034 -->
<!-- markdownlint-disable MD013 -->

# Kestrun - Third-Party Notices

**License:** [MIT](https://licenses.nuget.org/MIT) (SPDX: MIT)
**Copyright © $years** Kestrun Contributors

Kestrun is distributed under the MIT License.
This document lists third-party software components used by Kestrun, along with their licenses.

---
"@

# $sb is a [System.Text.StringBuilder] used to accumulate the markdown output
$sb = [System.Text.StringBuilder]::new()
# Add a note about the generation of this file
foreach ($line in $nugetLicenses ) {
    $null = $sb.AppendLine()
    $null = $sb.Append( ($line.TrimEnd() -replace 'ΓÇô', '-' -replace '┬⌐', '© '
            #-replace 'https://licenses.nuget.org/MIT', '[MIT](https://licenses.nuget.org/MIT)' `
            #-replace 'https://licenses.nuget.org/Apache-2.0', '[Apache-2.0](https://opensource.org/license/apache-2-0/)')
        )
    )
}


# --- Manual additions for source-included components (e.g., Cloudbase) ---
$manualSection = @'
---

## Manually Added Notices

The following components are not distributed via NuGet but are included in the Kestrun source tree:

### PowerShell-Yaml (derived)

- **Origin:** https://github.com/cloudbase/powershell-yaml
- **License:** [Apache-2.0](https://licenses.nuget.org/Apache-2.0)
- **Files:**
  - Adapted Pester test(s) under `tests/`
  - Portions of object conversion / serialization logic integrated into Kestrun
- **Notes:** Portions of code were directly adapted and translated into Kestrun.
  The original Apache-2.0 headers are preserved in relevant files.
  Additional inspiration was taken from the project’s handling of PowerShell objects.

'@

$manualSection += @'

### PoShLog (derived)

- **Origin:** https://github.com/PoShLog/PoShLog
- **License:** [MIT](https://licenses.nuget.org/MIT)
- **Files:** Modified logging components under `src/.../Logging`
- **Notes:** Heavily modified; original MIT copyright and license
  notices are preserved in derived files.
'@

# Combine everything
$kestrunHeader + ($sb.ToString()) + "`n" + $manualSection | Set-Content -Path $Path -Encoding UTF8

Write-Host "✅ Third-party notices generated at: $Path" -ForegroundColor Green
Write-Host '🔍 Please review the generated file for compliance with third-party licenses.'
