permissions:
    contents: read
    pull-requests: read

name: CI (main)

on:
    push:
        branches: [main]
        paths:
            - "**/*.cs"
            - "**/*.csproj"
            - "**/*.sln"
            - "**/*.ps1"
            - "**/*.psm1"
            - "**/*.psd1"
            - "**/*.yml"
            - "**/*.yaml"
            - tests/**
    workflow_dispatch: {}

jobs:
    ci:
        uses: Kestrun/Kestrun/.github/workflows/ci-core.yml@main
        with:
            is_pr: false
