permissions:
    contents: read
    pull-requests: read

name: CI (main)

on:
    push:
        branches: [main]
        paths:
            - src/**/*.cs
            - src/**/*.csproj
            - src/**/*.sln
            - src/**/*.ps1
            - src/**/*.psm1
            - src/**/*.psd1
    workflow_dispatch: {}

jobs:
    ci:
        uses: Kestrun/Kestrun/.github/workflows/ci-core.yml@main
        with:
            is_pr: false
        secrets:
            UPSTASH_REDIS_URL: ${{ secrets.UPSTASH_REDIS_URL }}
