permissions:
    contents: read
    pull-requests: read

name: Coverage (PR)

on:
    pull_request:
        branches: [main]
        types: [closed]
        paths:
            - "**/*.cs"
            - "**/*.csproj"
            - "**/*.sln"
            - "**/*.ps1"
            - "**/*.psm1"
            - "**/*.psd1"
            - "**/*.yml"
            - "**/*.yaml"
            - tests/**

jobs:
    coverage:
        uses: Kestrun/Kestrun/.github/workflows/coverage-core.yml@main
        with:
            is_pr: true
