permissions:
    contents: read
    pull-requests: read

name: Coverage (main)

on:
    push:
        branches: [main]
        paths:
            - "**/*.cs"
            - "**/*.csproj"
            - "**/*.sln"
            - "**/*.ps1"
            - "**/*.psm1"
            - "**/*.psd1"
            - "**/*.yml"
            - "**/*.yaml"
            - tests/**
    merge_group:
        types: [checks_requested]
    workflow_dispatch: {}

jobs:
    coverage:
        uses: Kestrun/Kestrun/.github/workflows/coverage-core.yml@main
        with:
            is_pr: false
