permissions:
  contents: read
name: .NET and PowerShell Tests

on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/*.ps1'
      - '**/*.psm1'
      - '**/*.psd1'
      - '**/*.yml'
      - '**/*.yaml'
      - tests/**
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/*.ps1'
      - '**/*.psm1'
      - '**/*.psd1'
      - '**/*.yml'
      - '**/*.yaml'
      - tests/**
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
        description: Enable debug logging

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    env:
      POWERSHELL_DISTRIBUTION_CHANNEL: GitHub-Actions

    steps:
    - name: 🛎️ Checkout
      uses: actions/checkout@v4

    - name: 🧰 Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        cache: true
        cache-dependency-path: |
          **/*.csproj
          **/packages.lock.json

    - name: 🧰 Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    # 🔊 Only enable super-verbose logs in debug runs
    - name: 🔧 Enable debug flags
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
      shell: bash
      run: |
        {
          echo "ACTIONS_STEP_DEBUG=true"
          echo "ACTIONS_RUNNER_DEBUG=true"
          echo "COREHOST_TRACE=1"
          echo "COREHOST_TRACE_VERBOSITY=3"
          echo "DOTNET_HOST_TRACE=1"
          echo "DOTNET_HOST_TRACE_VERBOSITY=3"
        } >> "$GITHUB_ENV"

    - name: 🧰 Install Module Invoke-Build
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Install-Module InvokeBuild -Force -Scope CurrentUser

    - name: 🧰 Install Module Pester (pin)
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Install-Module Pester -Force -Scope CurrentUser -RequiredVersion 5.6.1
        Get-Module Pester -ListAvailable | Select Name,Version,Path

    - name: 🔎 Print runtime context
      shell: pwsh
      run: |
        $PSVersionTable
        dotnet --info
        [System.Runtime.InteropServices.RuntimeInformation]::FrameworkDescription
        [System.Environment]::Version

    - name: 📦 Restore solution
      shell: pwsh
      run: dotnet restore ./Kestrun.sln

    # 🐛 Debug-only; non-fatal if it exits 1
    - name: 🔎 List Roslyn packages (transitive)
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
      continue-on-error: true
      shell: pwsh
      run: |
        dotnet list ./Kestrun.sln package --include-transitive --verbosity normal |
          Select-String -SimpleMatch "Microsoft.CodeAnalysis"
        Write-Host "Exit code was $LASTEXITCODE (ignored in debug)"

    # 🐛 Debug-only; non-fatal inventory
    - name: 📂 List Roslyn candidates in repo
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
      continue-on-error: true
      shell: pwsh
      run: |
        Get-ChildItem -Recurse -File -Include Microsoft.CodeAnalysis*.dll,System.Collections.Immutable*.dll,System.Reflection.Metadata*.dll |
          Sort-Object FullName |
          Select-Object FullName, Length |
          Format-Table -Auto

    - name: 🔧 Run C# Build (normal)
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        Invoke-Build Build

    # 🐛 Optional deep-dive build with binlog in debug (non-fatal)
    - name: 🧰 Debug build with binlog
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
      continue-on-error: true
      shell: pwsh
      run: |
        dotnet build ./Kestrun.sln -c Debug -bl:msbuild.binlog || $true

    # 🐛 Debug-only; force Roslyn load (non-fatal)
    - name: 🧪 Mini Roslyn sanity check (before Pester)
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug }}
      continue-on-error: true
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Continue'
        Import-Module ./src/PowerShell/Kestrun/Kestrun.psd1 -Force
        [AppDomain]::CurrentDomain.GetAssemblies() |
          Where-Object { $_.GetName().Name -like 'Microsoft.CodeAnalysis*' -or $_.GetName().Name -in 'System.Collections.Immutable','System.Reflection.Metadata' } |
          Select FullName, Location | Format-Table -Auto

        if ([type]::GetType('Kestrun.Scripting.CSharpDelegateBuilder')) {
          try { [Kestrun.Scripting.CSharpDelegateBuilder]::Compile('int x=1;') } catch { $_ | Out-String | Write-Host }
        }

    - name: 🧪 Run Tests
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        pwsh -NoLogo -NoProfile -Command 'Invoke-Build Test'

    - name: 📤 Upload diagnostics on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: diagnostics-${{ matrix.os }}
        path: |
          **/TestResults/**
          **/bin/**
          **/obj/project.assets.json
          src/PowerShell/Kestrun/**/*
          ./*.log
          ./msbuild.binlog

    # 🔐 Only open an interactive shell when YOU asked for debug and it failed
    - name: 🧑‍💻 Live SSH (only if failed and debug enabled)
      if: ${{ failure() && github.event_name == 'workflow_dispatch' && inputs.debug == 'true' }}
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
