name: .NET and PowerShell Tests

on:
  push:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/*.ps1'
      - '**/*.psm1'
      - '**/*.psd1'
      - '**/*.yml'
      - '**/*.yaml'
      - tests/**
  pull_request:
    paths:
      - '**/*.cs'
      - '**/*.csproj'
      - '**/*.sln'
      - '**/*.ps1'
      - '**/*.psm1'
      - '**/*.psd1'
      - '**/*.yml'
      - '**/*.yaml'
      - tests/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🛎️ Checkout
      uses: actions/checkout@v4

    - name: 🧰 Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: 🧰 Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: 🧪 Run C# Tests
      run: dotnet test tests/CSharp.Tests/Kestrun.Tests/KestrunTests.csproj

    - name: 🔧 Ensure Pester Installed
      shell: pwsh
      run: |
        if (-not (Get-Module -ListAvailable -Name Pester)) {
          Install-Module -Name Pester -Force -Scope CurrentUser
        }

    - name: 🧾 Log Pester Version
      shell: pwsh
      run: |
        Get-Module Pester -ListAvailable | Select-Object Name, Version, Path

    - name: 🧪 Run PowerShell Tests
      shell: pwsh
      run: Invoke-Pester -CI -Path tests/PowerShell.Tests/Kestrun.Tests
    