permissions:
    contents: read
    pull-requests: read

name: Format Check (PR)

on:
    pull_request:
        paths:
            - "**/*.cs"
            - "**/*.csproj"
            - "**/*.sln"
            - "**/*.ps1"
            - "**/*.psm1"
            - "**/*.psd1"
            - "**/*.yml"
            - "**/*.yaml"
            - tests/**

jobs:
    format-check:
        uses: ./.github/workflows/format-check-core.yml
        with:
            is_pr: true
