permissions:
    contents: read
    pull-requests: read

name: Lint (PR)

on:
    pull_request:
        paths:
            - "**/*.cs"
            - "**/*.csproj"
            - "**/*.sln"
            - "**/*.ps1"
            - "**/*.psm1"
            - "**/*.psd1"
            - "**/*.yml"
            - "**/*.yaml"
            - tests/**

jobs:
    lint:
        uses: Kestrun/Kestrun/.github/workflows/lint-core.yml@main
        with:
            is_pr: true
